"""Curated cross-border legal reference database (official sources + key points)."""

LEGAL_REFERENCES = [
    # ── KR ──
    {
        "country": "KR",
        "category": "개인정보",
        "title": "개인정보 보호법",
        "summary": "개인정보 수집·이용·제3자 제공·국외이전 시 동의/고지, 처리자·수탁자 구분, 재위탁 제한, 침해 통지 의무.",
        "url": "https://www.law.go.kr/법령/개인정보보호법",
        "keywords": "PIPA GDPR data privacy transfer",
    },
    {
        "country": "KR",
        "category": "세금",
        "title": "법인세법 / 조세특례제한법",
        "summary": "국내원천소득, 원천징수, PE(고정사업장), 조세조약 적용, 이전가격(국제조세조정), 부가가치세 전자적 용역.",
        "url": "https://www.law.go.kr/법령/법인세법",
        "keywords": "tax withholding VAT PE transfer pricing",
    },
    {
        "country": "KR",
        "category": "외환",
        "title": "외국환거래법",
        "summary": "대금 지급·수령, 해외 IP·로열티 송금, 대리결제/결제대행 시 신고·제한 가능성.",
        "url": "https://www.law.go.kr/법령/외국환거래법",
        "keywords": "FX payment agency proxy payment remittance",
    },
    {
        "country": "KR",
        "category": "컴플라이언스",
        "title": "부정청탁 및 금품등 수수의 금지에 관한 법률",
        "summary": "공무원·직원 대상 금품·접대·향응 금지, 재산상 이익 제공 제한.",
        "url": "https://www.law.go.kr/법령/부정청탁및금품등수수의금지에관한법률",
        "keywords": "bribery anti-corruption",
    },
    {
        "country": "KR",
        "category": "IP",
        "title": "특허법 / 저작권법",
        "summary": "직무발명·저작물 귀속, 양도·라이선스, 저작인격권, OSS 라이선스 준수.",
        "url": "https://www.law.go.kr/법령/저작권법",
        "keywords": "IP patent copyright work made for hire",
    },
    # ── US ──
    {
        "country": "US",
        "category": "개인정보",
        "title": "CCPA / CPRA (California)",
        "summary": "캘리포니아 소비자 개인정보 권리, DPA, opt-out, 데이터 판매·공유, B2B 서비스제공자 의무.",
        "url": "https://oag.ca.gov/privacy/ccpa",
        "keywords": "CPRA CCPA privacy California",
    },
    {
        "country": "US",
        "category": "세금",
        "title": "IRS – Withholding on Foreign Persons",
        "summary": "FDAP 소득 원천징수(FIRPTA·Chapter 3), W-8BEN/W-8BEN-E, 조세조약 감면, Form 1042-S.",
        "url": "https://www.irs.gov/individuals/international-taxpayers/tax-withholding-on-foreign-persons",
        "keywords": "withholding tax treaty W-8 FDAP",
    },
    {
        "country": "US",
        "category": "세금",
        "title": "State Sales Tax / Economic Nexus",
        "summary": "주별 판매세·SaaS 과세, Wayfair 이후 economic nexus, marketplace facilitator rules.",
        "url": "https://www.taxfoundation.org/data/all/state/sales-tax-rates/",
        "keywords": "sales tax nexus SaaS state tax",
    },
    {
        "country": "US",
        "category": "수출통제",
        "title": "EAR / ITAR (BIS & State Dept)",
        "summary": "듀얼유스·암호화·AI 반도체 등 수출·재수출·DE minimis, OFAC 제재, 최종사용자·최종용도.",
        "url": "https://www.bis.doc.gov/index.php/regulations/export-administration-regulations-ear",
        "keywords": "export control EAR ITAR OFAC sanctions",
    },
    {
        "country": "US",
        "category": "컴플라이언스",
        "title": "FCPA (Foreign Corrupt Practices Act)",
        "summary": "해외 공무원·국영기업 대상 뇌물 금지, accounting controls, third-party due diligence.",
        "url": "https://www.justice.gov/criminal-fraud/foreign-corrupt-practices-act",
        "keywords": "FCPA bribery anti-corruption",
    },
    {
        "country": "US",
        "category": "계약",
        "title": "UCC / Common Law Contract Principles",
        "summary": "준거법·분쟁해결(중재 AAA/ICC), limitation of liability, indemnity, warranty disclaimer.",
        "url": "https://www.law.cornell.edu/ucc",
        "keywords": "contract UCC governing law arbitration",
    },
    # ── JP ──
    {
        "country": "JP",
        "category": "개인정보",
        "title": "個人情報保護法 (APPI)",
        "summary": "개인정보 취급·제3자 제공·국외이전, PPC 가이드라인, 데이터 처리 agreement.",
        "url": "https://www.ppc.go.jp/en/",
        "keywords": "APPI privacy Japan transfer",
    },
    {
        "country": "JP",
        "category": "세금",
        "title": "法人税法 / 源泉徴収",
        "summary": "법인세, 원천징수, PE, 로열티·서비스 대가, 조세조약(한일).",
        "url": "https://www.nta.go.jp/english/index.htm",
        "keywords": "tax withholding treaty Japan",
    },
    # ── EU (DE as entry) ──
    {
        "country": "DE",
        "category": "개인정보",
        "title": "GDPR (EU) / BDSG",
        "summary": "DPA/SCC/ adequacy, 데이터주체 권리, DPIA, 국외이전 메커니즘, GDPR Art. 28 processor.",
        "url": "https://gdpr-info.eu/",
        "keywords": "GDPR SCC transfer DPA EU",
    },
    {
        "country": "DE",
        "category": "세금",
        "title": "EU VAT / OSS",
        "summary": "B2B 역과세, B2C 전자적 서비스 VAT, One-Stop-Shop, VAT ID validation.",
        "url": "https://taxation-customs.ec.europa.eu/taxation-1/value-added-tax-vat_en",
        "keywords": "VAT OSS EU digital services",
    },
    {
        "country": "GB",
        "category": "개인정보",
        "title": "UK GDPR / Data Protection Act 2018",
        "summary": "Brexit 후 UK GDPR, 국제이전 IDTA/SCC, ICO 가이드.",
        "url": "https://ico.org.uk/for-organisations/guide-to-data-protection/",
        "keywords": "UK GDPR privacy transfer",
    },
    {
        "country": "SG",
        "category": "개인정보",
        "title": "Personal Data Protection Act (PDPA)",
        "summary": "동의·목적 제한, 국외이전, DPO, PDPC enforcement.",
        "url": "https://www.pdpc.gov.sg/overview-of-pdpa/the-legislation/personal-data-protection-act",
        "keywords": "PDPA Singapore privacy",
    },
    {
        "country": "CN",
        "category": "데이터",
        "title": "个人信息保护法 (PIPL) / 数据安全法",
        "summary": "개인정보·중요데이터 국외 제공, CAC 보안평가, 현지화·재외국 송출 제한.",
        "url": "http://www.npc.gov.cn/npc/c30834/202108/a8c4e3672c74491a80bfc017901bbf14.shtml",
        "keywords": "PIPL China data localization cross-border",
    },
    {
        "country": "AU",
        "category": "개인정보",
        "title": "Privacy Act 1988 (APPs)",
        "summary": "Australian Privacy Principles, cross-border disclosure, NDB scheme.",
        "url": "https://www.oaic.gov.au/privacy/australian-privacy-principles",
        "keywords": "privacy Australia APP",
    },
    {
        "country": "CA",
        "category": "개인정보",
        "title": "PIPEDA / Quebec Law 25",
        "summary": "개인정보 동의, 국외 처리, 퀘벡 프랑스어·프라이버시 강화 규정.",
        "url": "https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/",
        "keywords": "PIPEDA Canada privacy Quebec",
    },
]
