# Generated by Django 5.2.17 on 2026-08-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meetingroom_join_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('keywords', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['country_code', 'category', 'title'],
                'indexes': [models.Index(fields=['country_code', 'category'], name='meetings_le_country_716330_idx')],
            },
        ),
    ]
