# Generated by Django 5.2.17 on 2026-08-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('room_id', models.UUIDField(db_index=True)),
                ('room_name', models.CharField(blank=True, max_length=100)),
                ('owner_uid', models.CharField(db_index=True, max_length=128)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='recording', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('videos', models.JSONField(default=dict)),
                ('participants', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['owner_uid', '-started_at'], name='meetings_re_owner_u_4c6de0_idx'), models.Index(fields=['room_id', 'session_id'], name='meetings_re_room_id_78c3cb_idx')],
            },
        ),
    ]
