server {
    listen 80;
    server_name 3-34-197-18.sslip.io 3.34.197.18;

    client_max_body_size 10M;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location /static/ {
        alias /opt/lion_meet/staticfiles/;
    }

    location / {
        return 301 https://3-34-197-18.sslip.io$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name 3-34-197-18.sslip.io;

    ssl_certificate /etc/letsencrypt/live/3-34-197-18.sslip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/3-34-197-18.sslip.io/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 10M;
    add_header Permissions-Policy "camera=*, microphone=*" always;

    location /static/ {
        alias /opt/lion_meet/staticfiles/;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
    }
}
